STUDENTS = [
    {"name": "Alice Chen", "email": "alice@lincolnhs.edu", "school": "Lincoln High School", "grade": "11th",
     "location": "Boston, MA",
     "bio": "Aspiring AI researcher. Trained my first CNN in 9th grade. Love applying ML to healthcare.",
     "interests": ["AI", "Healthcare", "Neuroscience"], "skills": ["Python", "TensorFlow", "Data Analysis"],
     "looking_for": ["Hackathon team", "Research mentor"],
     "reputation": {"projects_completed": 5, "reliability": 98}},
    {"name": "Bob Martinez", "email": "bob@westfield.edu", "school": "Westfield Academy", "grade": "12th",
     "location": "Boston, MA",
     "bio": "Frontend dev who ships. Built 3 apps used by my school. Design-obsessed.",
     "interests": ["Web Dev", "UI/UX", "Startups"], "skills": ["React", "TypeScript", "Figma"],
     "looking_for": ["Startup cofounder", "Hackathon team"],
     "reputation": {"projects_completed": 7, "reliability": 95}},
    {"name": "Charlie Okafor", "email": "charlie@stem-prep.edu", "school": "STEM Prep", "grade": "11th",
     "location": "New York, NY",
     "bio": "Biology + coding. Writing a research paper on gene expression. Science fair finalist.",
     "interests": ["Biology", "Genetics", "Research"], "skills": ["Research", "Writing", "R"],
     "looking_for": ["Research group", "Study partner"],
     "reputation": {"projects_completed": 4, "reliability": 100}},
    {"name": "Diana Park", "email": "diana@riverside.edu", "school": "Riverside High", "grade": "10th",
     "location": "San Francisco, CA",
     "bio": "Robotics captain. CAD wizard. FRC world championship qualifier.",
     "interests": ["Robotics", "Engineering", "CAD"], "skills": ["CAD", "SolidWorks", "Arduino", "C++"],
     "looking_for": ["Science fair team", "Hackathon team"],
     "reputation": {"projects_completed": 8, "reliability": 97}},
    {"name": "Ethan Wright", "email": "ethan@oakwood.edu", "school": "Oakwood School", "grade": "12th",
     "location": "New York, NY",
     "bio": "Founded a nonprofit teaching coding to kids. 200+ students taught. Debate champion.",
     "interests": ["Nonprofits", "Education", "Public Speaking"], "skills": ["Leadership", "Public Speaking", "JavaScript"],
     "looking_for": ["Nonprofit team", "Volunteers"],
     "reputation": {"projects_completed": 6, "reliability": 96}},
    {"name": "Fatima Al-Rashid", "email": "fatima@brighton.edu", "school": "Brighton Academy", "grade": "11th",
     "location": "Chicago, IL",
     "bio": "Math Olympiad medalist. Love algorithms and competitive programming.",
     "interests": ["Math", "Algorithms", "Competitive Programming"], "skills": ["C++", "Python", "Problem Solving"],
     "looking_for": ["Study partner", "Hackathon team"],
     "reputation": {"projects_completed": 3, "reliability": 99}},
    {"name": "George Kim", "email": "george@summit.edu", "school": "Summit High", "grade": "10th",
     "location": "San Francisco, CA",
     "bio": "Building indie games. Unity + pixel art. Dreaming of my own studio.",
     "interests": ["Game Dev", "Art", "Startups"], "skills": ["Unity", "C#", "Pixel Art"],
     "looking_for": ["Startup cofounder", "Designer"],
     "reputation": {"projects_completed": 5, "reliability": 93}},
    {"name": "Hana Suzuki", "email": "hana@centralhs.edu", "school": "Central High School", "grade": "12th",
     "location": "Boston, MA",
     "bio": "Neuroscience enthusiast heading to a summer research program. Loves data viz.",
     "interests": ["Neuroscience", "AI", "Psychology"], "skills": ["Python", "Data Analysis", "Writing"],
     "looking_for": ["Research group", "Research mentor"],
     "reputation": {"projects_completed": 4, "reliability": 98}},
]

PROJECTS = [
    {"owner": "Alice Chen", "members": ["Bob Martinez", "Charlie Okafor"], "title": "AI Plant Disease Detector", "category": "AI / Machine Learning",
     "description": "Building a mobile app that detects plant diseases from leaf photos using a CNN. Aiming to help small farmers. Need a frontend dev and a biology researcher.",
     "roles_needed": ["Frontend Developer", "Biology Researcher"], "skills": ["React", "TensorFlow", "Biology"],
     "timeline": "3 months", "status": "active", "progress": 45},
    {"owner": "Diana Park", "members": ["George Kim", "Fatima Al-Rashid"], "title": "Autonomous Recycling Robot", "category": "Robotics",
     "description": "A robot that sorts recyclables using computer vision. Competing in the state science fair. Looking for CV and embedded folks.",
     "roles_needed": ["Computer Vision Engineer", "Embedded Programmer"], "skills": ["Python", "Arduino", "CAD"],
     "timeline": "4 months", "status": "active", "progress": 30},
    {"owner": "Ethan Wright", "members": ["Hana Suzuki"], "title": "CodeForAll Nonprofit Platform", "category": "Nonprofit",
     "description": "A web platform to connect volunteer tutors with students who want to learn coding. Need developers and organizers.",
     "roles_needed": ["Full-stack Developer", "Community Organizer"], "skills": ["JavaScript", "Leadership"],
     "timeline": "Ongoing", "status": "active", "progress": 60},
    {"owner": "Bob Martinez", "members": ["George Kim"], "title": "StudyBuddy - AI Flashcards", "category": "Startups",
     "description": "An app that turns your notes into smart flashcards with spaced repetition. MVP done, need a cofounder to scale.",
     "roles_needed": ["Cofounder", "ML Engineer"], "skills": ["React", "Python"],
     "timeline": "6 months", "status": "active", "progress": 70},
    {"owner": "Charlie Okafor", "members": ["Hana Suzuki"], "title": "Gene Expression Research Paper", "category": "Research",
     "description": "Co-authoring a paper analyzing gene expression data. Looking for a data analyst comfortable with R.",
     "roles_needed": ["Data Analyst"], "skills": ["R", "Research", "Statistics"],
     "timeline": "5 months", "status": "completed", "progress": 100},
]

OPPORTUNITIES = [
    {"title": "MIT THINK Scholars Program", "org": "MIT", "type": "Research", "location": "Cambridge, MA",
     "description": "A research program for high schoolers with a passion for science, technology, engineering, and math.",
     "deadline": "2026-01-15", "tags": ["Research", "STEM"], "link": "https://think.mit.edu"},
    {"title": "Congressional App Challenge", "org": "U.S. Congress", "type": "Competition", "location": "Nationwide",
     "description": "Create an app and compete to have it displayed in the U.S. Capitol.",
     "deadline": "2026-11-01", "tags": ["Coding", "Competition"], "link": "https://congressionalappchallenge.us"},
    {"title": "Regeneron Science Talent Search", "org": "Society for Science", "type": "Scholarship", "location": "Nationwide",
     "description": "The nation's oldest science & math competition for high school seniors. $3M in awards.",
     "deadline": "2026-11-13", "tags": ["Research", "Scholarship"], "link": "https://www.societyforscience.org"},
    {"title": "Google Summer Code-in for Teens", "org": "Google", "type": "Internship", "location": "Remote",
     "description": "Contribute to open source and get mentored by industry engineers over the summer.",
     "deadline": "2026-03-01", "tags": ["Coding", "Open Source"], "link": "https://summerofcode.withgoogle.com"},
    {"title": "HackMIT 2026", "org": "MIT", "type": "Hackathon", "location": "Cambridge, MA",
     "description": "One of the largest student hackathons. Build something amazing in 24 hours.",
     "deadline": "2026-09-20", "tags": ["Hackathon", "Coding"], "link": "https://hackmit.org"},
    {"title": "Coca-Cola Scholars Program", "org": "Coca-Cola Foundation", "type": "Scholarship", "location": "Nationwide",
     "description": "$20,000 scholarship recognizing high school seniors for leadership and service.",
     "deadline": "2026-10-31", "tags": ["Scholarship", "Leadership"], "link": "https://www.coca-colascholarsfoundation.org"},
    {"title": "NYC Tech Talent Pipeline Internship", "org": "NYC Tech", "type": "Internship", "location": "New York, NY",
     "description": "A paid summer internship placing NYC high schoolers into local startups and tech teams.",
     "deadline": "2026-04-15", "tags": ["Internship", "Tech"], "link": "https://www.tech.nyc"},
    {"title": "Bay Area Youth Robotics League", "org": "SF Robotics", "type": "Competition", "location": "San Francisco, CA",
     "description": "A regional robotics competition for Bay Area high school teams. Build, compete, and win scholarships.",
     "deadline": "2026-05-10", "tags": ["Robotics", "Competition"], "link": "https://example.org/bayrobotics"},
    {"title": "Chicago Youth Research Symposium", "org": "UChicago", "type": "Research", "location": "Chicago, IL",
     "description": "Present your independent research to university faculty and win mentorship placements.",
     "deadline": "2026-06-01", "tags": ["Research", "STEM"], "link": "https://example.org/chicagosymposium"},
    {"title": "Boston Startup Weekend for Teens", "org": "Startup Boston", "type": "Hackathon", "location": "Boston, MA",
     "description": "Pitch, build, and launch a startup idea in 54 hours alongside other teen founders.",
     "deadline": "2026-08-22", "tags": ["Startups", "Hackathon"], "link": "https://example.org/bostonsw"},
]

FORUM = [
    {"author": "Diana Park", "community": "Robotics", "title": "Best budget microcontroller for a first robot?",
     "body": "My team is starting a new build and we're torn between Arduino and Raspberry Pi. What do you all recommend for computer vision tasks on a budget?",
     "upvotes": 24, "comments": [
         {"author": "Alice Chen", "text": "For CV specifically, a Raspberry Pi 4 handles OpenCV much better. Arduino is great for motor control though."},
         {"author": "Fatima Al-Rashid", "text": "We ran a hybrid: Pi for vision, Arduino for actuators. Best of both worlds."},
     ]},
    {"author": "Charlie Okafor", "community": "Research", "title": "How do you find a research mentor as a high schooler?",
     "body": "I want to publish before college but cold-emailing professors feels impossible. Any tips that actually worked for you?",
     "upvotes": 41, "comments": [
         {"author": "Hana Suzuki", "text": "Email PhD students, not professors! They're more responsive and often need help with data."},
         {"author": "Ethan Wright", "text": "Local universities have summer programs. That's how I got my first lab experience."},
     ]},
    {"author": "Bob Martinez", "community": "Startups", "title": "Is it worth incorporating a startup in high school?",
     "body": "My flashcard app is getting real users. Should I form an LLC now or wait? Worried about the legal stuff.",
     "upvotes": 18, "comments": [
         {"author": "George Kim", "text": "Wait until you have revenue. Focus on product first, paperwork later."},
     ]},
    {"author": "Fatima Al-Rashid", "community": "College Admissions", "title": "Balancing Olympiad prep with applications",
     "body": "Senior year is brutal. How are you all managing competition training while writing essays?",
     "upvotes": 33, "comments": [
         {"author": "Ethan Wright", "text": "Time-block ruthlessly. I do essays in the morning, competition math at night."},
     ]},
]
